name: "BunnyCDN storage deployer"
description: "BunnyCDN storage deployer"
inputs:
  source:
    description: "The source directory folder."
    required: true
  storageZoneName:
    description: "The name of your storage zone where you are connecting to."
    required: true
  accessKey:
    description: "The storage API key."
    required: true
  pullZoneId:
    description: "Is required for purging."
  pullZoneAccessKey:
    description: "Is required for purging."
  purge:
    description: "It will purge the pull zone if true. pullZoneId and pullZoneAccessKey should be provided."
    default: "false"
  remove:
    description: "It will remove the files from storage before uploading if 'true' provided."
    default: "false"

runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "upload-cloud"
  color: "orange"
